In [2]:
!pip install nba_api

Requirement already satisfied: nba_api in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (1.11.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from nba_api) (2.4.3)
Requirement already satisfied: pandas>=2.1.0 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from nba_api) (3.0.1)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from nba_api) (2.32.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from pandas>=2.1.0->nba_api) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from pandas>=2.1.0->nba_api) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2026.2.25)
Requirement already satisfied: six>=1.5 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.0->nba_api) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
from nba_api.stats.endpoints import leaguegamefinder

In [5]:
games = leaguegamefinder.LeagueGameFinder(
    season_nullable="2024-25"
)

df_2024_season_raw = games.get_data_frames()[0]

df_2024_season_raw.to_csv('nba_league_games_2024-25_raw.csv')

In [6]:
df_2024_season_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 2802 entries, 0 to 2801
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SEASON_ID          2802 non-null   str
 1   TEAM_ID            2802 non-null   int64
 2   TEAM_ABBREVIATION  2802 non-null   str
 3   TEAM_NAME          2802 non-null   str
 4   GAME_ID            2802 non-null   str
 5   GAME_DATE          2802 non-null   str
 6   MATCHUP            2802 non-null   str
 7   WL                 2802 non-null   str
 8   MIN                2802 non-null   int64
 9   PTS                2802 non-null   int64
 10  FGM                2802 non-null   int64
 11  FGA                2802 non-null   int64
 12  FG_PCT             2802 non-null   float64
 13  FG3M               2802 non-null   int64
 14  FG3A               2802 non-null   int64
 15  FG3_PCT            2802 non-null   float64
 16  FTM                2802 non-null   int64
 17  FTA                2802 non-null   int64
 18  FT_PCT             2796 non-null   float64
 19  OREB               2802 non-null   int64
 20  DREB               2802 non-null   int64
 21  REB                2802 non-null   int64
 22  AST                2802 non-null   int64
 23  STL                2802 non-null   int64
 24  BLK                2802 non-null   int64
 25  TOV                2802 non-null   int64
 26  PF                 2802 non-null   int64
 27  PLUS_MINUS         2802 non-null   float64
dtypes: float64(4), int64(17), str(7)
memory usage: 613.1 KB

In [7]:
df = df_2024_season_raw.copy()

# season_id

In [9]:
df['SEASON_ID'] = df['SEASON_ID'].astype(int)

In [37]:
df['SEASON_ID'].unique()

array([42024, 52024, 22024, 32024, 62024, 12024])

## 62024 NBA CUP

## 52024 Play-in Tournament

## 42024 playoff game

In [38]:
df_season_42024 = df[df['SEASON_ID']==42024]

In [39]:
df_season_42024

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,HOME_TEAM
0,42024,1610612754,IND,Indiana Pacers,42400407,2025-06-22,IND @ OKC,L,240,91,...,12,33,45,17,6,4,21,24,-12.0,False
1,42024,1610612760,OKC,Oklahoma City Thunder,42400407,2025-06-22,OKC vs. IND,W,240,103,...,13,27,40,20,14,8,7,23,12.0,True
2,42024,1610612754,IND,Indiana Pacers,42400406,2025-06-19,IND vs. OKC,W,240,108,...,11,35,46,23,16,5,10,17,17.0,True
3,42024,1610612760,OKC,Oklahoma City Thunder,42400406,2025-06-19,OKC @ IND,L,240,91,...,4,37,41,14,4,4,21,20,-17.0,False
4,42024,1610612760,OKC,Oklahoma City Thunder,42400405,2025-06-16,OKC vs. IND,W,239,120,...,19,26,45,24,15,12,11,24,11.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,42024,1610612746,LAC,LA Clippers,42400171,2025-04-19,LAC @ DEN,L,264,110,...,11,33,44,25,7,6,20,25,-2.0,False
164,42024,1610612754,IND,Indiana Pacers,42400131,2025-04-19,IND vs. MIL,W,239,117,...,5,38,43,28,6,6,5,22,19.0,True
165,42024,1610612765,DET,Detroit Pistons,42400121,2025-04-19,DET @ NYK,L,241,112,...,11,26,37,23,6,9,19,21,-11.0,False
166,42024,1610612752,NYK,New York Knicks,42400121,2025-04-19,NYK vs. DET,W,240,123,...,8,28,36,26,12,9,9,21,11.0,True
167,42024,1610612747,LAL,Los Angeles Lakers,42400161,2025-04-19,LAL vs. MIN,L,241,95,...,13,25,38,15,5,4,13,10,-22.0,True

In [40]:
df_season_52024 = df[df["SEASON_ID"]==52024]

In [41]:
df_season_52024.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,HOME_TEAM
168,52024,1610612742,DAL,Dallas Mavericks,52400211,2025-04-18,DAL @ MEM,L,239,106,...,7,29,36,25,9,8,16,17,-14.0,False
169,52024,1610612748,MIA,Miami Heat,52400201,2025-04-18,MIA @ ATL,W,266,123,...,13,41,54,33,4,8,14,15,9.0,False
170,52024,1610612763,MEM,Memphis Grizzlies,52400211,2025-04-18,MEM vs. DAL,W,241,120,...,16,34,50,30,8,4,10,17,14.0,True
171,52024,1610612737,ATL,Atlanta Hawks,52400201,2025-04-18,ATL vs. MIA,L,265,114,...,11,33,44,30,12,3,9,18,-9.0,True
172,52024,1610612748,MIA,Miami Heat,52400111,2025-04-16,MIA @ CHI,W,240,109,...,9,36,45,30,10,7,15,16,19.0,False

## 32024 All Star

## 22024 Regular Season

## 12024 Preseason

# team_id

# team_abbreviation

In [13]:
df['TEAM_ABBREVIATION'].unique()

<StringArray>
['IND', 'OKC', 'NYK', 'MIN', 'DEN', 'BOS', 'GSW', 'CLE', 'HOU', 'LAC', 'DET',
 'LAL', 'MIL', 'ORL', 'MIA', 'MEM', 'DAL', 'ATL', 'CHI', 'SAC', 'CHA', 'NOP',
 'PHX', 'BKN', 'UTA', 'TOR', 'PHI', 'SAS', 'POR', 'WAS', 'SHQ', 'CHK', 'KEN',
 'CAN', 'TMC', 'TMT', 'TMM', 'RCE', 'TMG', 'BND', 'ULM', 'NZB']
Length: 42, dtype: str

# team_name

In [15]:
df['TEAM_NAME'].unique()

<StringArray>
[        'Indiana Pacers',  'Oklahoma City Thunder',        'New York Knicks',
 'Minnesota Timberwolves',         'Denver Nuggets',         'Boston Celtics',
  'Golden State Warriors',    'Cleveland Cavaliers',        'Houston Rockets',
            'LA Clippers',        'Detroit Pistons',     'Los Angeles Lakers',
        'Milwaukee Bucks',          'Orlando Magic',             'Miami Heat',
      'Memphis Grizzlies',       'Dallas Mavericks',          'Atlanta Hawks',
          'Chicago Bulls',       'Sacramento Kings',      'Charlotte Hornets',
   'New Orleans Pelicans',           'Phoenix Suns',          'Brooklyn Nets',
              'Utah Jazz',        'Toronto Raptors',     'Philadelphia 76ers',
      'San Antonio Spurs', 'Portland Trail Blazers',     'Washington Wizards',
                   ' OGs',          ' Global Stars',           ' Young Stars',
          ' Rising Stars',                ' Team C',                ' Team T',
                ' Team M',              'Team Rice',         ' Team G League',
             'Team Bonds',         'Ratiopharm Ulm',   'New Zealand Breakers']
Length: 42, dtype: str

# GAME_ID

In [17]:
df['GAME_ID'] = df['GAME_ID'].astype(int)

# GAME_DATE

In [19]:
df['GAME_DATE'] = pd.to_datetime(df['GAME_DATE'], errors="raise")

# MATCHUP

either 'vs' or '@' in the middle indicating whether home and away team.

team with '@' means away team

team with 'vs' means home

In [21]:
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42024,1610612754,IND,Indiana Pacers,42400407,2025-06-22,IND @ OKC,L,240,91,...,0.759,12,33,45,17,6,4,21,24,-12.0
1,42024,1610612760,OKC,Oklahoma City Thunder,42400407,2025-06-22,OKC vs. IND,W,240,103,...,0.710,13,27,40,20,14,8,7,23,12.0
2,42024,1610612754,IND,Indiana Pacers,42400406,2025-06-19,IND vs. OKC,W,240,108,...,0.680,11,35,46,23,16,5,10,17,17.0
3,42024,1610612760,OKC,Oklahoma City Thunder,42400406,2025-06-19,OKC @ IND,L,240,91,...,0.808,4,37,41,14,4,4,21,20,-17.0
4,42024,1610612760,OKC,Oklahoma City Thunder,42400405,2025-06-16,OKC vs. IND,W,239,120,...,0.813,19,26,45,24,15,12,11,24,11.0

## Add column HOME_TEAM which will be boolean

game at home will be marked with a true

In [26]:
def isHomeGame(val) -> bool:
    return "vs" in val

In [28]:
df["HOME_TEAM"] = df['MATCHUP'].apply(isHomeGame)

In [35]:
home_games = df.loc[df["HOME_TEAM"]]

In [36]:
home_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,HOME_TEAM
1,42024,1610612760,OKC,Oklahoma City Thunder,42400407,2025-06-22,OKC vs. IND,W,240,103,...,13,27,40,20,14,8,7,23,12.0,True
2,42024,1610612754,IND,Indiana Pacers,42400406,2025-06-19,IND vs. OKC,W,240,108,...,11,35,46,23,16,5,10,17,17.0,True
4,42024,1610612760,OKC,Oklahoma City Thunder,42400405,2025-06-16,OKC vs. IND,W,239,120,...,19,26,45,24,15,12,11,24,11.0,True
7,42024,1610612754,IND,Indiana Pacers,42400404,2025-06-13,IND vs. OKC,L,240,104,...,7,26,33,21,11,3,15,27,-7.0,True
8,42024,1610612754,IND,Indiana Pacers,42400403,2025-06-11,IND vs. OKC,W,239,116,...,7,29,36,24,13,11,13,24,9.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2789,12024,1610612747,LAL,Los Angeles Lakers,12400009,2024-10-06,LAL vs. PHX,L,238,114,...,7,42,49,31,9,7,17,18,-4.0,True
2790,12024,1610612766,CHA,Charlotte Hornets,12400006,2024-10-06,CHA vs. NYK,L,241,109,...,8,38,46,27,3,6,19,24,-2.0,True
2794,12024,1610612746,LAC,LA Clippers,12400004,2024-10-05,LAC vs. GSW,L,239,90,...,9,38,47,21,11,6,20,14,-1.0,True
2797,12024,1610612747,LAL,Los Angeles Lakers,12400003,2024-10-04,LAL vs. MIN,L,241,107,...,4,34,38,28,9,12,20,20,-17.0,True
2800,12024,1610612762,UTA,Utah Jazz,12400002,2024-10-04,UTA vs. NZB,W,238,116,...,9,35,44,27,11,5,21,19,29.0,True

# Next